### ISSUE TITLE
consistent and best term for "custom DLC mod"/"content/DLC mods"/"DLC/mods"

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#20]
Naturally there are many mentions of custom DLC mods, e.g. the first one:
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/int.xaml#L34

However the term is not used consistently. It should be decided which is the best term, e.g. most easily understandable, sufficiently precise and least technical.

**Comment by Mgamerz** [comment]
Custom DLC is the same thing as DLC mod. Mod Manager uses a header called CUSTOMDLC to indicate a DLC mod, which was named as such simply because that's what I called it when DLC mods came out. To an end user they won't care, but a lot of strings about CUSTOMDLC are in reference to a Custom DLC task in Mod Manager, which are more developer oriented. It would be difficult to switch everything to only one or the other. Maybe a clarification where this string faces a more end-user would be better.

**Comment by Mgamerz** [comment]
I'm thinking of maybe adding glossary to the help menu that can contain a bunch of key terminology for users to browse, if they want. This could be updated outside of builds through the dynamic help system.
