### ISSUE TITLE
prompt to choose mod library directoy on first launch

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#24]
Don't wanna fill up user's system ssd with redundant mod copies.

Need to find a balance between "put this in your Documents" for write access and "put this somewhere appropriate for storage".

Maybe something along the lines of "if you have an ssd as system disk and an additonal hdd then choose somewhere on the hdd" should be added to the guide anyway.

It is my understanding that there is a mechanism to gain write access in place, this could also be applied to mod library directory if necessary.

**Comment by Mgamerz** [comment]
This would be to change the default. I am not a big fan of forcing user to change simply because I have seen far too ma ybusers put mod manager in dumb locations, like in the game directory or configuration files folder. Wipe your config or wipe your your game? Well everything is now gone (I've seen the happen multiple times in logs which is why it defaults to Documents).

**Comment by Mgamerz** [comment]
This has been implemented into the preview welcome panel, though it needs validation to see if it works out. There are a few remaining things that this panel will need to do such as prevent loading mods until the dialog has closed.

**Comment by HarHarLinks** [comment]
ping me for testing when you have a build :)

**Comment by Mgamerz** [comment]
Rolled into #27 

You can trigger dialog by deleting key 'ShowedWelcomeMessage2' from %programdata%\me3tweaksmodmanager\settings.ini and then restarting the app.
