### ISSUE TITLE
Remove Mod Update Checks after Mod Import

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/ME3TweaksModManager#263]
If you bulk download/import mods one after another, it will always bring up the mod update prompt after you choose to import or install a mod, sometimes even stack them.

**Comment by Mgamerz** [comment]
While I won't be disabling the update check, what I originally meant for this feature was to make it check that the imported mod was up to date, as sometimes even I put out mods that get a tiny update (since uploading to nexus is a lot of effort at times). I'll have this fixed so it's scoped only to the mod(s) that were imported.

**Comment by Mgamerz** [comment]
I'm pretty sure this is implemented in the current 8.0 beta code but I need to do some more testing to ensure it still runs.

**Comment by C0d3Deo** [comment]
> While I won't be disabling the update check, what I originally meant for this feature was to make it check that the imported mod was up to date, as sometimes even I put out mods that get a tiny update (since uploading to nexus is a lot of effort at times). I'll have this fixed so it's scoped only to the mod(s) that were imported.

This creates a burden for players who choose to use texture mods for their, which obviously doesn't allow further mod manipulation, but who like to use the mod manager to skip the game launcher. Please reconsider making this optional

**Comment by Mgamerz** [comment]
The update check is for mods in the library, not for what's installed, which the only thing texture modding affects.

**Comment by C0d3Deo** [comment]
> The update check is for mods in the library, not for what's installed, which the only thing texture modding affects.

Are you saying this is not the same issue this thread is pertaining to or that its simply not an "issue" at all? I don't understand how tyour response changes the situation considering you have to put the mods into the library to install them. I have to use ME3Tweaks to install mods. Once mods are installed it will check every time its opened for an update for every single mod listed no matter how incremental, and won't stop giving an initial popup, stopping me from launching the game like I want, until I close the box. I can understand the benefit to having it check by default, but to make it a forced, unremovable option seems counter to the spirit of the mod, putting an inconvenience players that literally CAN'T update mods anymore because of the textures system.

**Comment by Mgamerz** [comment]
Updates are checked for once a day. In Mod Manager 7 it checked for updates to all mods on any mod import, which is what this bug report is about. In Mod Manager 8 it only checks for updates to the mod that has been imported.

**Comment by Mgamerz** [comment]
This should be more reliable and consistent now in Mod Manager 8.
