### ISSUE TITLE
Feature Request: Add option to turn off mod update checks

### ISSUE THREAD

**Issue by C0d3Deo** [ME3Tweaks/ME3TweaksModManager#300]
Idea 1: A manual toggle option in settings
Idea 2: Detect if texture mods have been installed yet, then automatically turn off updates check, if so

There's an inconvenience to users who have many mods, and also use texture mods. You can't update any mods thereafter, but you'll be encouraged to do so by ME3Tweaks, every time it opens. If you use ME3T to skip the MELE launcher, you will be haunted for all of your days.

**Comment by Masamune3210** [comment]
The updates arent for the installed mods, its for the library, so the fact that there are mods installed or not is irrelevant. The solution is to just update your mods

**Comment by C0d3Deo** [comment]
So maybe I'm no understanding how texture mods affect this. But from what I read it was made pretty clear that NO MOD UPDATES WHATSOEVER can occur once you install texture mods, including even updates to existing mods.

If that is true, I wouldn't call what you're saying a solution to: restore my entire game back to vanilla, download the new mod updates, reinstall all my mods, scan my game directory, and reinstall all my textures, **every single time any given mod gets an update**, instead of just making it so the mod manager doesn't check for updates. May I ask why are you so vehemently against this idea? You seem to be fighting it pretty hard, and I truly don't understand. I'm not trying to be antagonistic

**Comment by Mgamerz** [comment]
You can update a mod in mod manager without applying it to a game.

**Comment by C0d3Deo** [comment]
Ok, so I wasn't understanding what you were saying before, but now I get it. Sorry about that. That said, I still think there's validity to my request. I currently have 65 mods installed for ME3. Again, knowing that I can't do anything once I install textures, it seems counter-intuitive to set up the users up for perpetual pointless internet fetch quests, when the manager could just not bother with checking for updates. 

Am I underestimating how difficult this is? I haven't coded in half a decade, but this would seem like something that could be rectified with like 5 lines of code. Like the amount typing dedicated to clarifying the library vs. installed miscom could've added the toggle already. I completely understand if you're focused on other things with the program, but it kind of seems like you're refusing the request outright, rather than taking it as a "low-hanging fruit" type thing. A lot of people might not care, but if it can help some and is easy to do, then why not?

Could you even just give me a hint of where I might be able play around in the source code and disable it for myself personally?

**Comment by Mgamerz** [comment]
I understand your viewpoint - you don't want to be bothered by update prompts if you are never going to update installed mods.

Part of it is that I don't want to implement every feature request because there is a support cost to all of it - localization for example means that adding 2 strings requires 5 people. Mod Manager is 10 years old now and it has 10 years of code it has to work with so it is not as simple as just commenting something out or wrapping it in an if statement.

If you'd like to implement it in a PR, you can find storage for it in Settings.cs, MainWindow.xaml.cs and M3LoadedMods.cs is where the check handling will occur. You would need to be on the M3Core branch because I'm not going to be issuing updates for future 7.x builds and the 8.x codebase has significantly changed.
