### ISSUE TITLE
Remove redundancy

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#311]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/f4155d20cf746b317a87b3e26e9509cd6ab32fd2/MassEffectModManagerCore/modmanager/localizations/int.xaml#L856
should be replaced by
https://github.com/ME3Tweaks/ME3TweaksCore/blob/dd90290c03f80ffbc2b829d617d7c141cf90f4b6/ME3TweaksCore/Localization/Dictionaries/int.xaml#L39

**Comment by Mgamerz** [comment]
This string is not used in M3 anymore. It's leftover from when M3 was split into M3 and M3Core - the core version of the backup service is actually mostly based off ALOT Installer's version, not M3's (7.x) version.

WPF is a bit difficult to find usages of strings since they can be dynamically accessed, however I don't see any references to this string key when I search for it. I'll remove it.
