### ISSUE TITLE
string_interp_XFilesNeedToBePatched

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#34]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/ebe4cde3f545366915d2952e398f3b4a1115207a/MassEffectModManagerCore/modmanager/localizations/int.xaml#L395

Maybe you can make this work in English (I don't see how: 1 file need**s** to be patched), but most other languages will have trouble, as you'd need to interpolate more than `number` and `file(s)`, e.g. one or both verbs.

**Comment by Mgamerz** [comment]
0 is the number of items, while 1 is either file (if the number is 1) or files (if the number is not 1). Tajfun indicated this will be an issue in polish because they use some wacked out numbering system with words, but I don't know how this could be fixed as it seems other localisations use a completely different sentence structure.

**Comment by HarHarLinks** [comment]
as the interpolation can't do it justice, i suggest removing it in favor of `{0} file(s) need(s) to be patched` or `need to patch {0} file(s)`.

**Comment by Tajfun403** [comment]
Writing alternate ending in brackets isn't really universal either. It'll look like a bit of mess even in English, not speaking about Polish and probably some other "advanced" languages.
I'd vote for `Amount of files that need to be patched: {0}`. It's not that nice, but I don't see other solution that wouldn't require language-specific rules.

**Comment by Mgamerz** [comment]
We'd need to see how it looks in things like Polish first since this seems to be localization dependent. I can do some checking but I am not sure if final tokens (in this case, {1}) need to exist, or if it just skips them. I beleive the first tokens have to be since they are simply parsed in that order.

E.g. In english
{0} {1} need to be patched
(which resolves to:
0 files need to be patched
1 file needs to be patched
2 files need to be patched
etc.
)


In another language:
Amount of files to be patched: {0}

**Comment by Mgamerz** [comment]
Remember you can move all of the tokens around as long as you keep the { }.

**Comment by Tajfun403** [comment]
How would word `need` change its form when it's not a variable, but a static string? (looking at your examples. Only `file` is variable)
I'm afraid changing word order ain't gonna change anything when translating original sentence to Polish. Maybe Mellin would have an idea on hacking it around, but I don't have any. Switching to `Amount of files to be patched: {0}` would be the only solution without ternary.
When we talked about it first, I gave you this wonderful bit of ternary on how would formatting original sentence in Polish look like (and yeah I don't have strength to reformat it :D)

`(x == 1) ? "{0} plik musi zostać naprawiony" : ( ( (x >= 2 && x < 5) || (x > 20 && (x % 10 >=2 && x % 10 < 5))) ? "{0} pliki muszą zostać naprawione" : "{0} plików musi zostać naprawionych" ), amountOfFiles.ToString()`

**Comment by HarHarLinks** [comment]
I agree with Tajfun's suggestion of `Amount of files that need to be patched: {0}` or similar formulation.
`Files to patch: {0}`

**Comment by Mgamerz** [comment]
Files to patch: {0} would be an acceptable alternative in english I think. There is one more instance of this type of language in M3, Patched X files.

**Comment by HarHarLinks** [comment]
If you're referring to 
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/4e6a5fe7b15b9c28bd75bf89ecd8bcf0612e5d85/MassEffectModManagerCore/modmanager/localizations/int.xaml#L403
then this is already very close to the proposed solution. It works in German as is, or `Patched files: {0}`.

**Comment by Mgamerz** [comment]
This was resolved to the following:

Number of files requiring patches: {0}

The PatchedXY is no longer used.
